spring:
  ai:
    anthropic:
      api-key: YOUR_ANTHROPIC_CLAUDE_API_KEY
      model: claude-3
      max-tokens: 1024
      temperature: 0.7
      top-p: 0.9
      stop-sequences:
        - "END"
      system: "You are an AI assistant that provides helpful responses."
      streaming: false
